# =============================================================================
# check_no_licensed.R — deterministic gate: no licensed (TomTom-derived)
# column may appear in anything that describes what the Dataverse deposit or
# the replication fixture CONTAINS.
#
#   Rscript replication/check_no_licensed.R [root] [extra files ...]
#
# Exits 0 when clean, 1 with file:line for every hit. Base R only, by design:
# it runs inside `audit_mirror.R`, which is the mirror's first gate and must
# work before any package install.
#
# -----------------------------------------------------------------------------
# WHY
# -----------------------------------------------------------------------------
# `traffic_*` columns are derived from TomTom MOVE data. They are licensed and
# not redistributable. The panel the deposit ships must therefore carry NONE of
# them, and neither may the fixture, the column contract, or the deposit
# specification. DATAVERSE_DEPOSIT.md says so in prose; this file makes it a
# machine check, so "we remembered to strip them" stops being a promise.
#
# -----------------------------------------------------------------------------
# WHAT COUNTS AS A HIT — and the one carve-out, stated plainly
# -----------------------------------------------------------------------------
# A hit is a CONCRETE licensed column name: `traffic_` followed by at least one
# name character (`traffic_daily_mean`, `traffic_mp_mean`, ...). Wildcard and
# regex forms (`traffic_*`, `^traffic_`) are NOT hits — they are how the
# exclusion is *stated*, and forbidding them would forbid documenting the rule.
#
# CARVE-OUT, exactly one: a bare catalogue BULLET (`- \`traffic_x\`` on its own
# line) inside a section whose heading mentions traffic. `panel_contract.md` is
# generated by sourcing the training code, and its outcome/covariate catalogue
# legitimately enumerates the five traffic outcomes the ESTIMATOR supports —
# that section documents the model, not the deposit. Nothing else is exempt:
# inside the same section, fenced blocks, table rows and prose are still
# scanned, so a licensed column smuggled into section 4's fetched-column set,
# into a table, or into a CSV header is caught. The T9b PR proves it with an
# executed negative test.
#
# CSV files get no carve-out at all: every field of the header row is checked.
# =============================================================================

.licensed_re <- "traffic_[A-Za-z0-9]"   # concrete column, not `traffic_*`

# Files whose CONTENT is scanned as markdown/prose (heading carve-out applies).
.LICENSED_MD_TARGETS <- c(
  "replication/panel_contract.md",
  "replication/DATAVERSE_DEPOSIT.md"
)
# Files whose HEADER ROW is scanned as data columns (no carve-out).
.LICENSED_CSV_TARGETS <- c(
  "replication/fixtures/panel.csv",
  "replication/data/panel.csv"          # present only after pull_dataverse.R
)

#' Heading level of a markdown line, or NA if it is not a heading.
.md_heading_level <- function(line) {
  m <- regmatches(line, regexpr("^#{1,6}(?= )", line, perl = TRUE))
  if (length(m) == 0L) NA_integer_ else nchar(m)
}

#' Lines of a markdown file that are in scope.
#'
#' Exempt = a bare catalogue bullet (`- \`traffic_x\`` and nothing else) sitting
#' inside a section whose heading mentions traffic. Everything else in that
#' section — fenced blocks, table rows, prose — is still scanned, so a licensed
#' column cannot hide by being filed under a traffic heading.
.md_in_scope <- function(lines) {
  catalogue_bullet <- "^\\s*[-*]\\s*`traffic_[A-Za-z0-9_]+`\\s*$"
  keep <- rep(TRUE, length(lines))
  in_traffic_section <- FALSE
  section_level <- NA_integer_
  for (i in seq_along(lines)) {
    lvl <- .md_heading_level(lines[[i]])
    if (!is.na(lvl)) {
      if (in_traffic_section && lvl <= section_level) in_traffic_section <- FALSE
      if (!in_traffic_section && grepl("traffic", lines[[i]], ignore.case = TRUE)) {
        in_traffic_section <- TRUE
        section_level <- lvl
      }
    }
    if (in_traffic_section && grepl(catalogue_bullet, lines[[i]], perl = TRUE)) {
      keep[[i]] <- FALSE
    }
  }
  keep
}

#' Findings as a character vector of "path:line  [id]  text" strings.
#' @param root repository root
#' @param extra additional file paths (repo-relative) to scan as markdown
check_no_licensed_findings <- function(root = ".", extra = character(0)) {
  out <- character(0)
  add <- function(p, i, id, txt) {
    out <<- c(out, sprintf("  %s:%d  [%s]  %s", p, i, id,
                           trimws(substr(txt, 1L, 140L))))
  }

  for (p in unique(c(.LICENSED_MD_TARGETS, extra))) {
    full <- file.path(root, p)
    if (!file.exists(full)) {
      # panel_contract.md / DATAVERSE_DEPOSIT.md are allowlisted and must exist;
      # a caller-supplied extra that is absent is a caller error either way.
      add(p, 0L, "missing", "expected file not found")
      next
    }
    lines <- readLines(full, warn = FALSE)
    keep <- .md_in_scope(lines)
    hits <- grep(.licensed_re, lines, perl = TRUE)
    for (h in hits) if (keep[[h]]) add(p, h, "licensed_column", lines[[h]])
  }

  for (p in .LICENSED_CSV_TARGETS) {
    full <- file.path(root, p)
    if (!file.exists(full)) next          # data/ is absent on a fresh clone
    hdr <- readLines(full, n = 1L, warn = FALSE)
    if (length(hdr) == 0L) next
    cols <- trimws(gsub('"', "", strsplit(hdr, ",", fixed = TRUE)[[1L]]))
    bad <- cols[grepl(.licensed_re, cols, perl = TRUE)]
    for (b in bad) add(p, 1L, "licensed_column", paste0("header column: ", b))
  }

  out
}

# --- script mode --------------------------------------------------------------
# sys.nframe() == 0 only when this file is executed at top level by Rscript;
# `source()` from audit_mirror.R pushes a frame, so the gate stays silent there.
if (sys.nframe() == 0L) {
  .args <- commandArgs(trailingOnly = TRUE)
  .root <- if (length(.args) >= 1L) .args[[1L]] else "."
  .extra <- if (length(.args) > 1L) .args[-1L] else character(0)
  .f <- check_no_licensed_findings(.root, .extra)
  if (length(.f) > 0L) {
    cat("check_no_licensed: FAIL — ", length(.f),
        " licensed-column finding(s):\n", sep = "")
    cat(paste(.f, collapse = "\n"), "\n", sep = "")
    quit(save = "no", status = 1L)
  }
  cat("check_no_licensed: OK — no TomTom-licensed `traffic_*` column in the",
      " deposit spec, the column contract, or the fixture header.\n", sep = "")
}
